//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobControlCenter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class RtcSandboxOperations : global::System.Configuration.ApplicationSettingsBase {
        
        private static RtcSandboxOperations defaultInstance = ((RtcSandboxOperations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RtcSandboxOperations())));
        
        public static RtcSandboxOperations Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\MetroTest")]
        public string Integration {
            get {
                return ((string)(this["Integration"]));
            }
            set {
                this["Integration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\DotNet")]
        public string Feature_Dev {
            get {
                return ((string)(this["Feature_Dev"]));
            }
            set {
                this["Feature_Dev"] = value;
            }
        }
    }
}
